<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQKHZZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQKHZZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRQKHZZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRQKHZZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRQKHZZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RQKHZZx',
    'container.build_id' => 'fff78e52',
    'container.build_time' => 1637999198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQKHZZx');
